theme = "dracula"

[editor]
line-number = "relative"
mouse = false
color-modes = true
true-color = true
shell = ["sh", "-c"]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
# display-inlay-hints = true

# or control each character
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "|"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
# tab = "→"

[editor.statusline]
left = ["mode", "spinner","version-control", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-g = [":write-all", ":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
C-o = [":open"]
C-s = [":w"]

[keys.normal.space]
# Toggle inline hints
"H" = ":toggle lsp.display-inlay-hints" 

