[language-server] 
biome = { command = "biome", args = ["lsp-proxy"] } # language server definition like in doc
snippets-ts = { command = "snippets-ls", args = ["-config", "/home/belozerskiy/.config/helix/typescript.json"]}

# [language-server.rust-analyzer.config.check]
# command = "clippy"

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "snippets-ts"] # like in doc
auto-format = true
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

